// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modbus.proto

package modbusgrpc

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ModbusRequest struct {
	Addr                 int32    `protobuf:"varint,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Cnt                  int32    `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModbusRequest) Reset()         { *m = ModbusRequest{} }
func (m *ModbusRequest) String() string { return proto.CompactTextString(m) }
func (*ModbusRequest) ProtoMessage()    {}
func (*ModbusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4384190c9e71792, []int{0}
}

func (m *ModbusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModbusRequest.Unmarshal(m, b)
}
func (m *ModbusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModbusRequest.Marshal(b, m, deterministic)
}
func (m *ModbusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModbusRequest.Merge(m, src)
}
func (m *ModbusRequest) XXX_Size() int {
	return xxx_messageInfo_ModbusRequest.Size(m)
}
func (m *ModbusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModbusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModbusRequest proto.InternalMessageInfo

func (m *ModbusRequest) GetAddr() int32 {
	if m != nil {
		return m.Addr
	}
	return 0
}

func (m *ModbusRequest) GetCnt() int32 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

type RegisterResponse struct {
	Data                 []int32  `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4384190c9e71792, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetData() []int32 {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ModbusRequest)(nil), "modbus.ModbusRequest")
	proto.RegisterType((*RegisterResponse)(nil), "modbus.RegisterResponse")
}

func init() { proto.RegisterFile("modbus.proto", fileDescriptor_f4384190c9e71792) }

var fileDescriptor_f4384190c9e71792 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcd, 0x4f, 0x49,
	0x2a, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x4c, 0xb9, 0x78,
	0x7d, 0xc1, 0xac, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xc4, 0x94,
	0x94, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0x39, 0x39,
	0xaf, 0x44, 0x82, 0x09, 0x2c, 0x04, 0x62, 0x2a, 0xa9, 0x71, 0x09, 0x04, 0xa5, 0xa6, 0x67, 0x16,
	0x97, 0xa4, 0x16, 0x05, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x82, 0x74, 0xa6, 0x24, 0x96,
	0x24, 0x4a, 0x30, 0x2a, 0x30, 0x83, 0x74, 0x82, 0xd8, 0x46, 0x51, 0x30, 0xe3, 0x83, 0x53, 0x8b,
	0xca, 0x32, 0x93, 0x53, 0x85, 0x3c, 0xb9, 0x44, 0x82, 0x52, 0x13, 0x53, 0x3c, 0xf2, 0x73, 0x52,
	0x32, 0xf3, 0xd2, 0x61, 0x66, 0x14, 0x0b, 0x89, 0xea, 0x41, 0x9d, 0x87, 0xe2, 0x1a, 0x29, 0x09,
	0x98, 0x30, 0xba, 0x6d, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x9f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x1b, 0xca, 0xb8, 0xde, 0xd9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModbusServiceClient is the client API for ModbusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModbusServiceClient interface {
	ReadHoldingRegisters(ctx context.Context, in *ModbusRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type modbusServiceClient struct {
	cc *grpc.ClientConn
}

func NewModbusServiceClient(cc *grpc.ClientConn) ModbusServiceClient {
	return &modbusServiceClient{cc}
}

func (c *modbusServiceClient) ReadHoldingRegisters(ctx context.Context, in *ModbusRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/modbus.ModbusService/ReadHoldingRegisters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModbusServiceServer is the server API for ModbusService service.
type ModbusServiceServer interface {
	ReadHoldingRegisters(context.Context, *ModbusRequest) (*RegisterResponse, error)
}

// UnimplementedModbusServiceServer can be embedded to have forward compatible implementations.
type UnimplementedModbusServiceServer struct {
}

func (*UnimplementedModbusServiceServer) ReadHoldingRegisters(ctx context.Context, req *ModbusRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadHoldingRegisters not implemented")
}

func RegisterModbusServiceServer(s *grpc.Server, srv ModbusServiceServer) {
	s.RegisterService(&_ModbusService_serviceDesc, srv)
}

func _ModbusService_ReadHoldingRegisters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModbusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModbusServiceServer).ReadHoldingRegisters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/modbus.ModbusService/ReadHoldingRegisters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModbusServiceServer).ReadHoldingRegisters(ctx, req.(*ModbusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModbusService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "modbus.ModbusService",
	HandlerType: (*ModbusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadHoldingRegisters",
			Handler:    _ModbusService_ReadHoldingRegisters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modbus.proto",
}
